apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicleMaintanance-service-deployment
  labels:
    service: vehicleMaintanance-service
spec:
  selector:
    matchLabels:
      app: vehicleMaintanance-service-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: vehicleMaintanance-service-deployment
    spec:
      containers:
      - name: vehicleMaintanance-service-image
        image: inseegocontainerregistryqa.azurecr.io/vehicleMaintanance-service-rc:latest
        resources:
          requests:
            cpu: 400m
        env:
         - name: LogEventLevel
           value: "DEBUG"
         - name: LogTablename
           value: "DashboardService"
        envFrom:
         - configMapRef:
            name: platform-service-config
         - secretRef:
            name: platform-service-secret
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: vehicleMaintanance-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: vehicleMaintanance-service-deployment
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: vehicleMaintanance-service-hpa
    namespace: default
spec:
    maxReplicas: 4
    minReplicas: 1
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: vehicleMaintanance-service-deployment
    targetCPUUtilizationPercentage: 80

