<template>
    <div>
        {{this.$tc("Dashboard.RiskyDriver.Menu.ToolTip")}}
        {{this.$tc("Dashboard.RiskyDriver.DefaultHeader.Name")}}
        {{this.$tc("Dashboard.RiskyDriver.DefaultHeader.Overspeeding.Tooltip")}}
        {{this.$tc("Dashboard.RiskyDriver.DefaultHeader.Overspeeding.WidgetDescription")}}
        {{this.$tc("Dashboard.RiskyDriver.DefaultHeader.HarshBreaking.Tooltip")}}
        {{this.$tc("Dashboard.RiskyDriver.DefaultHeader.HarshBreaking.WidgetDescription")}}
        {{this.$tc("Dashboard.RiskyDriver.DefaultHeader.HarshAcceleration.Tooltip")}}
        {{this.$tc("Dashboard.RiskyDriver.DefaultHeader.HarshAcceleration.WidgetDescription")}}
        {{this.$tc("Dashboard.RiskyDriver.DefaultHeader.HarshCornering.Tooltip")}}
        {{this.$tc("Dashboard.RiskyDriver.DefaultHeader.HarshCornering.WidgetDescription")}}
        {{this.$tc("Dashboard.RiskyDriver.DefaultHeader.ContinuousDriving.Tooltip")}}
        {{this.$tc("Dashboard.RiskyDriver.DefaultHeader.ContinuousDriving.WidgetDescription")}}
        {{this.$tc("Dashboard.RiskyDriver.DefaultHeader.NightDriving.Tooltip")}}
        {{this.$tc("Dashboard.RiskyDriver.DefaultHeader.NightDriving.WidgetDescription")}}
        {{this.$tc("Dashboard.RiskyDriver.Widgets.Name")}}
        {{this.$tc("Dashboard.RiskyDriver.Body.NetworkChart.Tooltip")}}
        {{this.$tc("Dashboard.RiskyDriver.Body.NetworkChart.WidgetDescription")}}
        {{this.$tc("Dashboard.RiskyDriver.Body.NetworkChart.WidgetProvider")}}
        {{this.$tc("Dashboard.RiskyDriver.Body.RatingChart.Tooltip")}}
        {{this.$tc("Dashboard.RiskyDriver.Body.RatingChart.WidgetDescription")}}
        {{this.$tc("Dashboard.RiskyDriver.Body.RatingChart.WidgetProvider")}}
        {{this.$tc("Dashboard.RiskyDriver.Body.HistoryChart.Tooltip")}}
        {{this.$tc("Dashboard.RiskyDriver.Body.HistoryChart.WidgetDescription")}}
        {{this.$tc("Dashboard.RiskyDriver.Body.HistoryChart.WidgetProvider")}}
        {{this.$tc("Dashboard.RiskyDriver.Body.IncidentVsMilesChart.Tooltip")}}
        {{this.$tc("Dashboard.RiskyDriver.Body.IncidentVsMilesChart.WidgetDescription")}}
        {{this.$tc("Dashboard.RiskyDriver.Body.IncidentVsMilesChart.WidgetProvider")}}
        {{this.$tc("Dashboard.RiskyDriver.Body.RiskChart.Tooltip")}}
        {{this.$tc("Dashboard.RiskyDriver.Body.RiskChart.WidgetDescription")}}
        {{this.$tc("Dashboard.RiskyDriver.Body.RiskChart.WidgetProvider")}}
        {{this.$tc("Dashboard.RiskyDriver.Data.NetworkChart.Overspeeding.Name")}}
        {{this.$tc("Dashboard.RiskyDriver.Data.NetworkChart.HA.Name")}}
        {{this.$tc("Dashboard.RiskyDriver.Data.NetworkChart.HC.Name")}}
        {{this.$tc("Dashboard.RiskyDriver.Data.NetworkChart.HB.Name")}}
        {{this.$tc("Dashboard.RiskyDriver.Data.NetworkChart.DrillDown.Title")}}
        {{this.$tc("Dashboard.RiskyDriver.Data.RatingChart.ChartTitle")}}
        {{this.$tc("Dashboard.RiskyDriver.Data.RatingChart.Green")}}
        {{this.$tc("Dashboard.RiskyDriver.Data.RatingChart.Yellow")}}
        {{this.$tc("Dashboard.RiskyDriver.Data.RatingChart.Red")}}
        {{this.$tc("Dashboard.RiskyDriver.Data.RatingChart.DrillDown.Title")}}
        {{this.$tc("Dashboard.RiskyDriver.Data.HistoryChart.ChartTitle")}}
        {{this.$tc("Dashboard.RiskyDriver.Data.HistoryChart.ChartTitleDuration.Year")}}
        {{this.$tc("Dashboard.RiskyDriver.Data.HistoryChart.ChartTitleDuration.Days.Item1")}}
        {{this.$tc("Dashboard.RiskyDriver.Data.HistoryChart.ChartTitleDuration.Days.Item2")}}
        {{this.$tc("Dashboard.RiskyDriver.Data.HistoryChart.Overspeeding.Name")}}
        {{this.$tc("Dashboard.RiskyDriver.Data.HistoryChart.HA.Name")}}
        {{this.$tc("Dashboard.RiskyDriver.Data.HistoryChart.HB.Name")}}
        {{this.$tc("Dashboard.RiskyDriver.Data.HistoryChart.HC.Name")}}
        {{this.$tc("Dashboard.RiskyDriver.Data.HistoryChart.DrillDown.Title")}}
        {{this.$tc("Dashboard.RiskyDriver.Data.RiskChart.ChartTitle")}}
        {{this.$tc("Dashboard.RiskyDriver.Data.RiskChart.Title")}}
        {{this.$tc("Dashboard.RiskyDriver.Data.RiskChart.BottomTitle")}}
        {{this.$tc("Dashboard.RiskyDriver.Data.RiskChart.Color.TooltipDescription.Item1")}}
        {{this.$tc("Dashboard.RiskyDriver.Data.RiskChart.Color.TooltipDescription.Item2")}}
        {{this.$tc("Dashboard.RiskyDriver.Data.RiskChart.Intersection.TooltipDescription.Item1")}}
        {{this.$tc("Dashboard.RiskyDriver.Data.RiskChart.Intersection.TooltipDescription.Item2")}}
        {{this.$tc("Dashboard.RiskyDriver.Data.RiskChart.Intersection.Color.TooltipDescription")}}
        {{this.$tc("Dashboard.RiskyDriver.Data.RiskChart.DrillDown.Title")}}
        {{this.$tc("Dashboard.RiskyDriver.Data.IncedentVsMiles.ChartTitle")}}
        {{this.$tc("Dashboard.RiskyDriver.Data.IncedentVsMiles.ChartTitleDuration.Days.Item1")}}
        {{this.$tc("Dashboard.RiskyDriver.Data.IncedentVsMiles.ChartTitleDuration.Days.Item2")}}
        {{this.$tc("Dashboard.RiskyDriver.Data.IncedentVsMiles.ChartTitleDuration.Year")}}
        {{this.$tc("Dashboard.RiskyDriver.Data.IncedentVsMiles.Worst.Name")}}
        {{this.$tc("Dashboard.RiskyDriver.Data.IncedentVsMiles.Best.Name")}}
        {{this.$tc("Dashboard.RiskyDriver.Data.IncedentVsMiles.RegressionLine.Name")}}
        {{this.$tc("Dashboard.RiskyDriver.Data.IncedentVsMiles.Driver.Name")}}
        {{this.$tc("Dashboard.RiskyDriver.Data.IncedentVsMiles.DrillDown.Title")}}
        {{this.$tc("Dashboard.RiskyDriver.Data.IncedentVsMiles.Chart.ToolTip.OSCount")}}
        {{this.$tc("Dashboard.RiskyDriver.Data.IncedentVsMiles.Chart.ToolTip.HBCount")}}
        {{this.$tc("Dashboard.RiskyDriver.Data.IncedentVsMiles.Chart.ToolTip.ORCount")}}
        {{this.$tc("Dashboard.RiskyDriver.Data.IncedentVsMiles.Chart.ToolTip.HACount")}}
        {{this.$tc("Dashboard.RiskyDriver.Data.IncedentVsMiles.Chart.ToolTip.HCCount")}}
        {{this.$tc("Dashboard.RiskyDriver.Data.IncedentVsMiles.Chart.ToolTip.XICount")}}
        {{this.$tc("Dashboard.RiskyDriver.Data.IncedentVsMiles.Chart.YAxisTitle.Name")}}
        {{this.$tc("Dashboard.RiskyDriver.Body.Header.Overspeeding.Title.Name")}}
        {{this.$tc("Dashboard.RiskyDriver.Body.Header.HA.Title.Name")}}
        {{this.$tc("Dashboard.RiskyDriver.Body.Header.HB.Title.Name")}}
        {{this.$tc("Dashboard.RiskyDriver.Body.Header.HC.Title.Name")}}
        {{this.$tc("Dashboard.RiskyDriver.Body.Header.ContinuousDriving.Title.Name")}}
        {{this.$tc("Dashboard.RiskyDriver.Body.Header.NightDriving.Title.Name")}}
        {{this.$tc("Dashboard.RiskyDriver.Data.RiskChart.Chart.Dictionary.Distance")}}
        {{this.$tc("Dashboard.RiskyDriver.Data.RiskChart.Chart.Dictionary.TripCount")}}
        {{this.$tc("Dashboard.RiskyDriver.Data.RiskChart.Chart.Dictionary.ExcessiveIdling")}}
        {{this.$tc("Dashboard.RiskyDriver.Data.RiskChart.Chart.Dictionary.HarshBreaking")}}
        {{this.$tc("Dashboard.RiskyDriver.Data.RiskChart.Chart.Dictionary.HarshAcceleration")}}
        {{this.$tc("Dashboard.RiskyDriver.Data.RiskChart.Chart.Dictionary.HarshCornering")}}
        {{this.$tc("Dashboard.RiskyDriver.Data.RiskChart.Chart.Dictionary.Overspeeding")}}
    </div>
    <div>
        {{this.$tc("Dashboard.Executive.Menu.ToolTip")}}
        {{this.$tc("Dashboard.Executive.Body.Name")}}
        {{this.$tc("Dashboard.Executive.Body.OverSpeeding.Tooltip")}}
        {{this.$tc("Dashboard.Executive.Body.OverSpeeding.WidgetDescription")}}
        {{this.$tc("Dashboard.Executive.Body.OverSpeeding.WidgetProvider")}}
        {{this.$tc("Dashboard.Executive.Body.HAHBHC.Tooltip")}}
        {{this.$tc("Dashboard.Executive.Body.HAHBHC.WidgetDescription")}}
        {{this.$tc("Dashboard.Executive.Body.HAHBHC.WidgetProvider")}}
        {{this.$tc("Dashboard.Executive.Body.Idling.Tooltip")}}
        {{this.$tc("Dashboard.Executive.Body.Idling.WidgetDescription")}}
        {{this.$tc("Dashboard.Executive.Body.Idling.WidgetProvider")}}
        {{this.$tc("Dashboard.Executive.Body.NoGoGeoFence.Tooltip")}}
        {{this.$tc("Dashboard.Executive.Body.NoGoGeoFence.WidgetDescription")}}
        {{this.$tc("Dashboard.Executive.Body.NoGoGeoFence.WidgetProvider")}}
        {{this.$tc("Dashboard.Executive.Body.MissedLateJobs.Tooltip")}}
        {{this.$tc("Dashboard.Executive.Body.MissedLateJobs.WidgetDescription")}}
        {{this.$tc("Dashboard.Executive.Body.MissedLateJobs.WidgetProvider")}}
        {{this.$tc("Dashboard.Executive.Body.DriverBehaviour.Tooltip")}}
        {{this.$tc("Dashboard.Executive.Body.DriverBehaviour.WidgetDescription")}}
        {{this.$tc("Dashboard.Executive.Body.DriverBehaviour.WidgetProvider")}}
        {{this.$tc("Dashboard.Executive.Body.Mileage.Tooltip")}}
        {{this.$tc("Dashboard.Executive.Body.Mileage.WidgetDescription")}}
        {{this.$tc("Dashboard.Executive.Body.Mileage.WidgetProvider")}}
        {{this.$tc("Dashboard.Executive.Body.VehicleNotStarted.Tooltip")}}
        {{this.$tc("Dashboard.Executive.Body.VehicleNotStarted.WidgetDescription")}}
        {{this.$tc("Dashboard.Executive.Body.VehicleNotStarted.WidgetProvider")}}
        {{this.$tc("Dashboard.Executive.Data.OverSpeeding.WidgetTitle")}}
        {{this.$tc("Dashboard.Executive.Data.OverSpeeding.Seriesdata.Last")}}
        {{this.$tc("Dashboard.Executive.Data.OverSpeeding.Seriesdata.This")}}
        {{this.$tc("Dashboard.Executive.Data.OverSpeeding.DrillDown.Title")}}
        {{this.$tc("Dashboard.Executive.Data.OverSpeeding.DrillDown.PopupTitle")}}
        {{this.$tc("Dashboard.Executive.Data.OverSpeeding.DrillDown.ChartTitle")}}
        {{this.$tc("Dashboard.Executive.Data.OverSpeeding.DrillDown.GridTitle")}}
        {{this.$tc("Dashboard.Executive.Data.OverSpeeding.DrillDown.ChartNarrative.Item1")}}
        {{this.$tc("Dashboard.Executive.Data.OverSpeeding.DrillDown.ChartNarrative.Item2")}}
        {{this.$tc("Dashboard.Executive.Data.OverSpeeding.DrillDown.ChartNarrative.Item3")}}
        {{this.$tc("Dashboard.Executive.Data.OverSpeeding.DrillDown.ChartNarrative.Item4")}}
        {{this.$tc("Dashboard.Executive.Data.OverSpeeding.DrillDown.ChartNarrative.Item5")}}
        {{this.$tc("Dashboard.Executive.Data.OverSpeeding.DrillDown.ChartNarrative.Item6")}}
        {{this.$tc("Dashboard.Executive.Data.OverSpeeding.DrillDown.ChartNarrative.Item7")}}
        {{this.$tc("Dashboard.Executive.Data.OverSpeeding.DrillDown.ChartNarrative.Item8")}}
        {{this.$tc("Dashboard.Executive.Data.OverSpeeding.Name")}}
        {{this.$tc("Dashboard.Executive.Data.OverSpeeding.DrillDown.ChartDrill.Item1")}}
        {{this.$tc("Dashboard.Executive.Data.OverSpeeding.DrillDown.ChartDrill.Item2")}}
        {{this.$tc("Dashboard.Executive.Data.OverSpeeding.DrillDown.ChartDrill.Item3")}}
        {{this.$tc("Dashboard.Executive.Data.OverSpeeding.DrillDown.ChartDrill.Item4")}}
        {{this.$tc("Dashboard.Executive.Data.IdlingChart.Idling.WidgetTitle")}}
        {{this.$tc("Dashboard.Executive.Data.IdlingChart.Seriesdata.Last")}}
        {{this.$tc("Dashboard.Executive.Data.IdlingChart.Seriesdata.This")}}
        {{this.$tc("Dashboard.Executive.Data.IdlingChart.DrillDown.Title")}}
        {{this.$tc("Dashboard.Executive.Data.IdlingChart.DrillDown.PopupTitle")}}
        {{this.$tc("Dashboard.Executive.Data.IdlingChart.DrillDown.ChartTitle")}}
        {{this.$tc("Dashboard.Executive.Data.IdlingChart.DrillDown.GridTitle")}}
        {{this.$tc("Dashboard.Executive.Data.IdlingChart.DrillDown.OffenderDriver.Item1")}}
        {{this.$tc("Dashboard.Executive.Data.IdlingChart.DrillDown.OffenderDriver.Item2")}}
        {{this.$tc("Dashboard.Executive.Data.IdlingChart.DrillDown.OffenderDrivers.Item1")}}
        {{this.$tc("Dashboard.Executive.Data.IdlingChart.DrillDown.OffenderDrivers.Item2")}}
        {{this.$tc("Dashboard.Executive.Data.IdlingChart.DrillDown.ChartNarrative.OffenderDriver.Item1")}}
        {{this.$tc("Dashboard.Executive.Data.IdlingChart.DrillDown.ChartNarrative.OffenderDriver.Item2")}}
        {{this.$tc("Dashboard.Executive.Data.IdlingChart.DrillDown.ChartNarrative.OffenderDriver.Item3")}}
        {{this.$tc("Dashboard.Executive.Data.IdlingChart.DrillDown.ChartNarrative.OffenderDriver.Item4")}}
        {{this.$tc("Dashboard.Executive.Data.IdlingChart.DrillDown.ChartNarrative.OffenderDriver.Item5")}}
        {{this.$tc("Dashboard.Executive.Data.Idling.Name")}}
        {{this.$tc("Dashboard.Executive.Data.ViolationChart.HA.Name")}}
        {{this.$tc("Dashboard.Executive.Data.ViolationChart.HB.Name")}}
        {{this.$tc("Dashboard.Executive.Data.ViolationChart.HC.Name")}}
        {{this.$tc("Dashboard.Executive.Data.ViolationChart.WidgetTitle")}}
        {{this.$tc("Dashboard.Executive.Data.ViolationChart.DrillDown.Title")}}
        {{this.$tc("Dashboard.Executive.Data.ViolationChart.DrillDown.PopupTitle")}}
        {{this.$tc("Dashboard.Executive.Data.ViolationChart.DrillDown.ChartTitle")}}
        {{this.$tc("Dashboard.Executive.Data.ViolationChart.DrillDown.GridTitle")}}
        {{this.$tc("Dashboard.Executive.Data.ViolationChart.ChartDrill.Name")}}
        {{this.$tc("Dashboard.Executive.Data.ViolationChart.DrillDown.ChartNarrative.OffenderDriver.Item1")}}
        {{this.$tc("Dashboard.Executive.Data.ViolationChart.DrillDown.ChartNarrative.OffenderDriver.Item2")}}
        {{this.$tc("Dashboard.Executive.Data.ViolationChart.DrillDown.ChartNarrative.OffenderDriver.Item3")}}
        {{this.$tc("Dashboard.Executive.Data.DriverBehaviourChart.Seriesdata.Last")}}
        {{this.$tc("Dashboard.Executive.Data.DriverBehaviourChart.Seriesdata.This")}}
        {{this.$tc("Dashboard.Executive.Data.DriverBehaviourChart.WidgetTitle")}}
        {{this.$tc("Dashboard.Executive.Data.DriverBehaviourChart.DrillDown.Title")}}
        {{this.$tc("Dashboard.Executive.Data.DriverBehaviourChart.DrillDown.PopupTitle")}}
        {{this.$tc("Dashboard.Executive.Data.DriverBehaviourChart.DrillDown.ChartTitle")}}
        {{this.$tc("Dashboard.Executive.Data.DriverBehaviourChart.DrillDown.GridTitle")}}
        {{this.$tc("Dashboard.Executive.Data.DriverBehaviourChart.ChartDrill.DriverBehaviour.Name")}}
        {{this.$tc("Dashboard.Executive.Data.DriverBehaviourChart.DrillDown.OffenderDriver.Item1")}}
        {{this.$tc("Dashboard.Executive.Data.DriverBehaviourChart.DrillDown.OffenderDriver.Item2")}}
        {{this.$tc("Dashboard.Executive.Data.DriverBehaviourChart.DrillDown.OffenderDrivers.Item1")}}
        {{this.$tc("Dashboard.Executive.Data.DriverBehaviourChart.DrillDown.OffenderDrivers.Item2")}}
        {{this.$tc("Dashboard.Executive.Data.DriverBehaviourChart.DrillDown.ChartNarrative.OffenderDriver.Item1")}}
        {{this.$tc("Dashboard.Executive.Data.DriverBehaviourChart.DrillDown.ChartNarrative.OffenderDriver.Item2")}}
        {{this.$tc("Dashboard.Executive.Data.DriverBehaviourChart.DrillDown.ChartNarrative.OffenderDriver.Item3")}}
        {{this.$tc("Dashboard.Executive.Data.DriverBehaviourChart.DrillDown.ChartNarrative.OffenderDriver.Item4")}}
        {{this.$tc("Dashboard.Executive.Data.DriverBehaviourChart.DrillDown.ChartNarrative.OffenderDriver.Item5")}}
        {{this.$tc("Dashboard.Executive.Data.DriverBehaviourChart.DrillDown.ChartNarrative.OffenderDriver.Item6")}}
        {{this.$tc("Dashboard.Executive.Data.DriverBehaviourChart.DrillDown.ChartNarrative.OffenderDriver.Item7")}}
        {{this.$tc("Dashboard.Executive.Data.DriverBehaviourChart.DrillDown.ChartNarrative.OffenderDriver.Item8")}}
        {{this.$tc("Dashboard.Executive.Data.VehicleNotStartedChart.WidgetTitle")}}
        {{this.$tc("Dashboard.Executive.Data.VehicleNotStartedChart.Seriesdata.Last")}}
        {{this.$tc("Dashboard.Executive.Data.VehicleNotStartedChart.Seriesdata.This")}}
        {{this.$tc("Dashboard.Executive.Data.MileageChart.WidgetTitle")}}
        {{this.$tc("Dashboard.Executive.Data.MileageChart.Seriesdata.Last")}}
        {{this.$tc("Dashboard.Executive.Data.MileageChart.Seriesdata.This")}}
        {{this.$tc("Dashboard.Executive.Data.MileageChart.Drivers.Name")}}
        {{this.$tc("Dashboard.Executive.Data.MileageChart.Vehicles.Name")}}
        {{this.$tc("Dashboard.Executive.Data.MileageChart.Mileage.Name")}}
        {{this.$tc("Dashboard.Executive.Data.MileageChart.DrillDown.Title")}}
        {{this.$tc("Dashboard.Executive.Data.MileageChart.DrillDown.PopupTitle")}}
        {{this.$tc("Dashboard.Executive.Data.MileageChart.DrillDown.ChartTitle")}}
        {{this.$tc("Dashboard.Executive.Data.MileageChart.DrillDown.GridTitle")}}
        {{this.$tc("Dashboard.Executive.Data.MileageChart.Seriesdata.Mileage.Name")}}
        {{this.$tc("Dashboard.Executive.Data.MileageChart.DrillDown.OffenderDriver.Item1")}}
        {{this.$tc("Dashboard.Executive.Data.MileageChart.DrillDown.OffenderDriver.Item2")}}
        {{this.$tc("Dashboard.Executive.Data.MileageChart.DrillDown.OffenderDrivers.Item1")}}
        {{this.$tc("Dashboard.Executive.Data.MileageChart.DrillDown.OffenderDrivers.Item2")}}
        {{this.$tc("Dashboard.Executive.Data.MileageChart.DrillDown.ChartNarrative.OffenderDriver.Item1")}}
        {{this.$tc("Dashboard.Executive.Data.MileageChart.DrillDown.ChartNarrative.OffenderDriver.Item2")}}
        {{this.$tc("Dashboard.Executive.Data.MileageChart.DrillDown.ChartNarrative.OffenderDriver.Item3")}}
        {{this.$tc("Dashboard.Executive.Data.MileageChart.DrillDown.ChartNarrative.OffenderDriver.Item4")}}
        {{this.$tc("Dashboard.Executive.Data.MileageChart.DrillDown.ChartNarrative.OffenderDriver.Item5")}}
        {{this.$tc("Dashboard.Executive.Data.MileageChart.DrillDown.ChartNarrative.OffenderDriver.Item6")}}
        {{this.$tc("Dashboard.Executive.Data.MileageChart.DrillDown.ChartNarrative.OffenderDriver.Item7")}}
        {{this.$tc("Dashboard.Executive.Data.MileageChart.DrillDown.ChartNarrative.OffenderDriver.Item8")}}
        {{this.$tc("Dashboard.Executive.Data.MileageChart.DrillDown.ChartNarrative.OffenderDriver.Item9")}}
        {{this.$tc("Dashboard.Executive.Data.MileageChart.DrillDown.ChartNarrative.OffenderDriver.Item10")}}
        {{this.$tc("Dashboard.Executive.Data.VehicleNotStartedChart.Seriesdata.Item1.This")}}
        {{this.$tc("Dashboard.Executive.Data.VehicleNotStartedChart.Seriesdata.Item2.This")}}
        {{this.$tc("Dashboard.Executive.Data.VehicleNotStartedChart.Seriesdata.Item1.Last")}}
        {{this.$tc("Dashboard.Executive.Data.VehicleNotStartedChart.Seriesdata.Item2.Last")}}
    </div>
    <div>
        {{this.$tc("Dashboard.Utilization.Menu.ToolTip")}}
        {{this.$tc("Dashboard.Utilization.DefaultHeader.Name")}}
        {{this.$tc("Dashboard.Utilization.DefaultHeader.VehicleUtilization.Tooltip")}}
        {{this.$tc("Dashboard.Utilization.DefaultHeader.VehicleUtilization.WidgetDescription")}}
        {{this.$tc("Dashboard.Utilization.DefaultHeader.DriverUtilization.Tooltip")}}
        {{this.$tc("Dashboard.Utilization.DefaultHeader.DriverUtilization.WidgetDescription")}}
        {{this.$tc("Dashboard.Utilization.DefaultHeader.DriveTime.Tooltip")}}
        {{this.$tc("Dashboard.Utilization.DefaultHeader.DriveTime.WidgetDescription")}}
        {{this.$tc("Dashboard.Utilization.DefaultHeader.DriveTimeVehiclePerDay.Tooltip")}}
        {{this.$tc("Dashboard.Utilization.DefaultHeader.DriveTimeVehiclePerDay.WidgetDescription")}}
        {{this.$tc("Dashboard.Utilization.DefaultHeader.MilesDriven.Tooltip")}}
        {{this.$tc("Dashboard.Utilization.DefaultHeader.MilesDriven.WidgetDescription")}}
        {{this.$tc("Dashboard.Utilization.DefaultHeader.MilesPerVehicle.Tooltip")}}
        {{this.$tc("Dashboard.Utilization.DefaultHeader.MilesPerVehicle.WidgetDescription")}}
        {{this.$tc("Dashboard.Utilization.DefaultHeader.BPMileage.Tooltip")}}
        {{this.$tc("Dashboard.Utilization.DefaultHeader.BPMileage.WidgetDescription")}}
        {{this.$tc("Dashboard.Utilization.Body.Name")}}
        {{this.$tc("Dashboard.Utilization.Body.DriveTimeIdleTimePie.Tooltip")}}
        {{this.$tc("Dashboard.Utilization.Body.DriveTimeIdleTimePie.WidgetDescription")}}
        {{this.$tc("Dashboard.Utilization.Body.DriveTimeIdleTimePie.WidgetProvider")}}
        {{this.$tc("Dashboard.Utilization.Body.DriveTimeIdleTimeHistory.Tooltip")}}
        {{this.$tc("Dashboard.Utilization.Body.DriveTimeIdleTimeHistory.WidgetDescription")}}
        {{this.$tc("Dashboard.Utilization.Body.DriveTimeIdleTimeHistory.WidgetProvider")}}
        {{this.$tc("Dashboard.Utilization.Body.BusinessPrivatePie.Tooltip")}}
        {{this.$tc("Dashboard.Utilization.Body.BusinessPrivatePie.WidgetDescription")}}
        {{this.$tc("Dashboard.Utilization.Body.BusinessPrivatePie.WidgetProvider")}}
        {{this.$tc("Dashboard.Utilization.Body.BusinessPrivateHistory.Tooltip")}}
        {{this.$tc("Dashboard.Utilization.Body.BusinessPrivateHistory.WidgetDescription")}}
        {{this.$tc("Dashboard.Utilization.Body.BusinessPrivateHistory.WidgetProvider")}}
        {{this.$tc("Dashboard.Utilization.Body.TripsMileTimeChart.Tooltip")}}
        {{this.$tc("Dashboard.Utilization.Body.TripsMileTimeChart.WidgetDescription")}}
        {{this.$tc("Dashboard.Utilization.Body.TripsMileTimeChart.WidgetProvider")}}
        {{this.$tc("Dashboard.Utilization.Body.VehicleUtilizationMostLeast.Tooltip")}}
        {{this.$tc("Dashboard.Utilization.Body.VehicleUtilizationMostLeast.WidgetDescription")}}
        {{this.$tc("Dashboard.Utilization.Body.VehicleUtilizationMostLeast.WidgetProvider")}}
        {{this.$tc("Dashboard.Utilization.Body.UtilizationByGroup.Tooltip")}}
        {{this.$tc("Dashboard.Utilization.Body.UtilizationByGroup.WidgetDescription")}}
        {{this.$tc("Dashboard.Utilization.Body.UtilizationByGroup.WidgetProvider")}}
        {{this.$tc("Dashboard.Utilization.Body.MilesDrivenMostLeast.Tooltip")}}
        {{this.$tc("Dashboard.Utilization.Body.MilesDrivenMostLeast.WidgetDescription")}}
        {{this.$tc("Dashboard.Utilization.Body.MilesDrivenMostLeast.WidgetProvider")}}
        {{this.$tc("Dashboard.Utilization.Body.MilesDrivenPerDayMostLeast.Tooltip")}}
        {{this.$tc("Dashboard.Utilization.Body.MilesDrivenPerDayMostLeast.WidgetDescription")}}
        {{this.$tc("Dashboard.Utilization.Body.MilesDrivenPerDayMostLeast.WidgetProvider")}}
        {{this.$tc("Dashboard.Utilization.Data.BusinessPrivateHistory.ChartTitle")}}
        {{this.$tc("Dashboard.Utilization.Data.BusinessPrivateHistory.ChartAltTitleCaption")}}
        {{this.$tc("Dashboard.Utilization.Data.BusinessPrivateHistory.BusinessMiles.Name")}}
        {{this.$tc("Dashboard.Utilization.Data.BusinessPrivateHistory.PrivateMiles.Name")}}
        {{this.$tc("Dashboard.Utilization.Data.BusinessPrivateHistory.TotalMiles.Name")}}
        {{this.$tc("Dashboard.Utilization.Data.BusinessPrivateChart.ChartTitle")}}
        {{this.$tc("Dashboard.Utilization.Data.BusinessPrivateChart.Business.Name")}}
        {{this.$tc("Dashboard.Utilization.Data.BusinessPrivateChart.Private.Name")}}
        {{this.$tc("Dashboard.Utilization.Data.DriveTimeIdleTimeChart.ChartTitle")}}
        {{this.$tc("Dashboard.Utilization.Data.DriveTimeIdleTimeChart.ChartSubTitle")}}
        {{this.$tc("Dashboard.Utilization.Data.DriveTimeIdleTimeChart.DriveTime.Name")}}
        {{this.$tc("Dashboard.Utilization.Data.DriveTimeIdleTimeChart.IdleTime.Name")}}
        {{this.$tc("Dashboard.Utilization.Data.MostLeastChart.ChartTitle")}}
        {{this.$tc("Dashboard.Utilization.Data.MostLeastChart.Most.Name")}}
        {{this.$tc("Dashboard.Utilization.Data.MostLeastChart.Least.Name")}}
        {{this.$tc("Dashboard.Utilization.Data.DriveTimeIdleTimeHistory.ChartTitle")}}
        {{this.$tc("Dashboard.Utilization.Data.DriveTimeIdleTimeHistory.ChartTitleDuration")}}
        {{this.$tc("Dashboard.Utilization.Data.DriveTimeIdleTimeHistory.ChartAltTitleCaption")}}
        {{this.$tc("Dashboard.Utilization.Data.DriveTimeIdleTimeHistory.DriveTime.Name")}}
        {{this.$tc("Dashboard.Utilization.Data.DriveTimeIdleTimeHistory.IdleTime.Name")}}
        {{this.$tc("Dashboard.Utilization.Data.MilesDrivenPerDayMostLeast.ChartTitle")}}
        {{this.$tc("Dashboard.Utilization.Data.MilesDrivenPerDayMostLeast.Most.Name")}}
        {{this.$tc("Dashboard.Utilization.Data.MilesDrivenPerDayMostLeast.Least.Name")}}
        {{this.$tc("Dashboard.Utilization.Data.TripMilesTime.ChartTitle.Item1")}}
        {{this.$tc("Dashboard.Utilization.Data.TripMilesTime.ChartTitle.Item2")}}
        {{this.$tc("Dashboard.Utilization.Data.TripMilesTime.Trips.Name")}}
        {{this.$tc("Dashboard.Utilization.Data.TripMilesTime.Time.Name")}}
        {{this.$tc("Dashboard.Utilization.Body.Header.DriveTime.Title.Name")}}
        {{this.$tc("Dashboard.Utilization.Body.Header.Driven.Title.Name")}}
        {{this.$tc("Dashboard.Utilization.Body.Header.VehiclePerDay.Title.Name")}}
        {{this.$tc("Dashboard.Utilization.Body.Header.DrivePerVehiclePerDay.Title.Name")}}
        {{this.$tc("Dashboard.Utilization.Body.Header.VehicleUtilization.Title.Name")}}
        {{this.$tc("Dashboard.Utilization.Body.Header.DriverUtilization.Title.Name")}}
        {{this.$tc("Dashboard.Utilization.Body.Header.Business.Title.Name")}}
        {{this.$tc("Dashboard.Utilization.Body.Header.Private.Title.Name")}}
        {{this.$tc("Dashboard.Utilization.Data.BusinessPrivate.DrillDown.Title")}}
        {{this.$tc("Dashboard.Utilization.Data.DriveTimeIdleTime.DrillDown.Title")}}
        {{this.$tc("Dashboard.Utilization.Data.TripsMileTime.DrillDown.Title")}}
        {{this.$tc("Dashboard.Utilization.Data.UtilizationByGroupMostLeast.DrillDown.Title")}}
        {{this.$tc("Dashboard.Utilization.Data.UtilizationByGroup.DrillDown.Title")}}
        {{this.$tc("Dashboard.Utilization.Data.MilesDrivenMostLeast.DrillDown.Title")}}
        {{this.$tc("Dashboard.Utilization.Data.MostAndLeastUtilizationByGroup.ChartTitle.Lowest")}}
        {{this.$tc("Dashboard.Utilization.Data.MostAndLeastUtilizationByGroup.ChartTitle.Highest")}}
        {{this.$tc("Dashboard.Utilization.Data.MostAndLeastUtilizationByGroup.Most.Name")}}
        {{this.$tc("Dashboard.Utilization.Data.MostAndLeastUtilizationByGroup.Least.Name")}}
        {{this.$tc("Dashboard.Utilization.Data.UtilizationByGroup.ChartTitle")}}
        {{this.$tc("Dashboard.Utilization.Data.UtilizationByGroup.GroupAverage.Name")}}

    </div>
    <div>
        {{this.$tc("Dashboard.Efficiency.Menu.ToolTip")}}
    </div>
    <div>
        {{this.$tc("Dashboard.LeagueTable.Column.Vehicle")}}
        {{this.$tc("Dashboard.LeagueTable.Column.DriverFirst")}}
        {{this.$tc("Dashboard.LeagueTable.Column.DriverLast")}}
        {{this.$tc("Dashboard.LeagueTable.Column.Overspeeding")}}
        {{this.$tc("Dashboard.LeagueTable.Column.Category1")}}
        {{this.$tc("Dashboard.LeagueTable.Column.Category2")}}
        {{this.$tc("Dashboard.LeagueTable.Column.Category3")}}
        {{this.$tc("Dashboard.LeagueTable.Column.HarshAcceleration")}}
        {{this.$tc("Dashboard.LeagueTable.Column.HarshBraking")}}
        {{this.$tc("Dashboard.LeagueTable.Column.HarshCornering")}}
        {{this.$tc("Dashboard.LeagueTable.Column.ExcessiveIdling")}}
        {{this.$tc("Dashboard.LeagueTable.Column.BusinessTime")}}
        {{this.$tc("Dashboard.LeagueTable.Column.BusinessMiles")}}
        {{this.$tc("Dashboard.LeagueTable.Column.PrivateTime")}}
        {{this.$tc("Dashboard.LeagueTable.Column.PrivateMiles")}}
        {{this.$tc("Dashboard.LeagueTable.Column.AllMiles")}}
        {{this.$tc("Dashboard.LeagueTable.Column.TotalDriveTime")}}
        {{this.$tc("Dashboard.LeagueTable.Column.ContinuousDriving")}}
        {{this.$tc("Dashboard.LeagueTable.Column.AfterHoursDriving")}}
        {{this.$tc("Dashboard.LeagueTable.Column.AverageScore")}}
        {{this.$tc("Dashboard.LeagueTable.Column.MilesPerEvent")}}
        {{this.$tc("Dashboard.LeagueTable.Column.GeofenceViolations")}}
        {{this.$tc("Dashboard.LeagueTable.Column.MissedOrLateJobs")}}
        {{this.$tc("Dashboard.LeagueTable.Column.VehicleNotStarted")}}
        {{this.$tc("Dashboard.LeagueTable.Column.VehicleNotReported")}}
        {{this.$tc("Dashboard.LeagueTable.Column.MPG")}}
        {{this.$tc("Dashboard.LeagueTable.Column.FuelConsumption")}}
        {{this.$tc("Dashboard.LeagueTable.Column.FuelCost")}}
        {{this.$tc("Dashboard.LeagueTable.Column.CarbonFootprint")}}
        {{this.$tc("Dashboard.LeagueTable.Column.SeatbeltViolations")}}
        {{this.$tc("Dashboard.LeagueTable.Column.UtilizationPerDays")}}
        {{this.$tc("Dashboard.LeagueTable.Column.UtilizationPercentage")}}
        {{this.$tc("Dashboard.LeagueTable.Column.Trips")}}
        {{this.$tc("Dashboard.LeagueTable.Column.AvgMilePerTrip")}}
        {{this.$tc("Dashboard.LeagueTable.Column.AvgMileKmPerTrip")}}
        {{this.$tc("Dashboard.LeagueTable.Column.DriverScore")}}
        {{this.$tc("Dashboard.LeagueTable.Column.TotalIdleTime")}}
        {{this.$tc("Dashboard.LeagueTable.Column.DriveTimePercentage")}}
        {{this.$tc("Dashboard.LeagueTable.Column.IdleTimePercentage")}}
    </div>
</template>
<script>
    exportdefault: {
        name: "DasboardService"
    };
</script>

